### ISSUE TITLE
\pict with \picprop fails

### ISSUE THREAD

**Issue by pgodwin** [erdomke/RtfPipe#17]
Getting a `NotSupportedException` when loading RTF documents with a picture with inline shape data. 

`ch` = 115 ('s') 

```
System.NotSupportedException: Specified method is not supported.
   at RtfPipe.HexBuffer.Append(Int32 ch)
   at RtfPipe.Parser.<Tokens>d__16.MoveNext()
   at RtfPipe.Parser.Parse()
   at RtfPipe.Rtf.ToHtml(RtfSource source, XmlWriter writer, RtfHtmlSettings settings)
   at RtfPipe.Rtf.ToHtml(RtfSource source, RtfHtmlSettings settings)
   at RtfDecoder.RtfDecode.Decode(String rtf, OutputFormat outputFormat) in C:\Users\godwinpe\source\repos\rtfdecode\RtfDecoder\RtfDecode.cs:line 87
   at TestDecoder.Program.Main(String[] args) in C:\Users\godwinpe\source\repos\rtfdecode\TestDecoder\Program.cs:line 16
```
Attached is a sample RTF:
[img-test.zip](https://github.com/erdomke/RtfPipe/files/2584046/img-test.zip)

```
{\rtf1\ansi\ansicpg1252\uc1\deff1{
\pict{\*\picprop\shplid1025{\sp{\sn shapeType}{\sv 75}}{\sp{\sn fFlipH}{\sv 0}}
{\sp{\sn fFlipV}{\sv 0}}{\sp{\sn fRotateText}{\sv 1}}{\sp{\sn pictureGray}{\sv 0}}{\sp{\sn pictureBiLevel}{\sv 0}}{\sp{\sn fFilled}{\sv 0}}{\sp{\sn fLine}{\sv 0}}{\sp{\sn wzName}{\sv Picture 0}}{\sp{\sn wzDescription}{\sv Linke
dIn.gif}}{\sp{\sn fHidden}{\sv 0}}{\sp{\sn fLayoutInCell}{\sv 1}}}\picscalex100\picscaley100\piccropl0\piccropr0\piccropt0\piccropb0\picw423\pich423\picwgoal240\pichgoal240\pngblip\bliptag-2141941385{\*\blipuid 805491778dc9ac8b2c298bd64da9d8ee}
89504e470d0a1a0a0000000d4948445200000010000000100803000000282d0f530000001974455874536f667477617265004d6963726f736f6674204f666669
63657fed357100000300504c54450000000f7fba0678b60b7ab70a7ab7137db80374b30676b40273b3157eb90d7bb70070b20072b3006eb00175b40f7cb80979
b60070b10778b6006db0006fb10074b40979b70777b5006caf0073b3006baf0676b50878b60274b30073b2006eb1006aae006cb00476b40d78b40b79b70d77b4
1e8abe1b85bd1281bb1a85bd1a84bc1d86bd1680ba1881bb1f84bc228abf258bbf3d97c72e90c22d90c23393c43192c43393c53293c52d90c32f91c33494c534
95c53595c53091c3248dc0268ec13f9bc82e91c3228bc02d91c33193c4248cc0268dc1228cc0258dc0328fc24099c9469cca489ecb489dcb4a9ecb4098c8489f
cb409bc84399c84f9fcb4499c850a0cd5ea9d25ca8d152a2cd52a3ce59a5cf5fa8d059a6ce5aa5ce78b4d77ab5d879b5d878b3d764aad27eb8da79b5d97bb6da
67abd27db9db60aad362abd37fbcdb69add38abfdd8cbfdd85bbdc82badc81badc84bbdc84bedc85bddc87bedc89bfdd84bddb86bedc82bcdb86bddc85bcdb8f
c3df8bc0dd8ac0dd8dc1de9ac9e39ecae39ac8e19ac9e2b1d7e9beddedb0d5e9a4cfe5a6d0e6bddbecbcdbecbadaecb9daeba3cee5c2dfeec7e1f0c7e2f0cde5
f1d4e8f3cfe5f2d8eaf4cee5f1cde4f1cce4f1cbe3f1d8ebf5c4e0eed7eaf4f9fdffeaf4f9e6f2f8e9f4f9f6fbfdf5fafdf2f8fceef6fbffffff010203010203
01020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301
02030102030102030102030102030102030102030102030102030102030102030102030102030102030102030102030102030102030102030102030102030102
03010203010203010203010203010203010203010203010203010203010203010203010203010203010203010203010203010203010203010203010203010203
01020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301020301
02030102030102030102030102037566e5d70000000174524e530040e6d86600000009704859730000004000000040006243635b0000000c636d50504a436d70
3037313200000003480073bc0000010549444154285363c8898b8f4f4880a2f8c45c86a4bce494d4fcfc0210c8cf2f4c63080d4befab0fcf8082cc080643affe
c5b323bd7d80c0d7c7c7cf9fc1c8386b4eb389a9a999b985a595b58d2d83be9dbd83a393b38bab5b40a09abb8701833a63d1dc168dd6796d1316cf6fd7d4d266
d061aa5e3c91b977f1e2050b172f8e62d1656065ab593c89bd63f1643dcf458b8b393819b8b84b164fe1e95cdcc0cb37757129373f83006fd9e269825d8b1b79
f9a62f2ee765661012ae583c4da47b7193b0e8f4c595c2620ce212b58b67f0ce5cdc2321396b719d940083b448505536777455b08864765588880c83ac9cbc82
84a4a282b0248f8482bc9c120383b20a12508d050054e2529f941a8ee10000000049454e44ae426082}
}
```

Another example:
```
\pict{\*\picprop{\sp{\sn shapeType}{\sv 75}}{\sp{\sn fFlipH}{\sv 0}}{\sp{\sn fFlipV}{\sv 0}}{\sp{\sn wzName}{\sv Picture 2}}{\sp{\sn fLayoutInCell}{\sv 1}}}\jpegblip\picw8784\pich3784\picwgoal4980\pichgoal2145\picscalex22\picscaley20 
<data>
}

Manually removing the picprop section seems to fix it.

**Comment by pgodwin** [comment]
Thanks @erdomke that 65ed841796a8bc52178e9d59ef36a76fed8830b6 looks like an eloquent fix. 

Internally I was looking to parse out shape properties to potentially apply some transforms to images it applies to. Shape property names and values appear to me to be a little bit weird, with the value in the tag group. Currently, I'm doing an explicit check for `sn` and `sv` values in `ReadControlWord()`, and passing the value on to `GetControlWord()` to handle. 

Would you think this is an appropriate place to do it, or is there a better place for it?

```
diff --git a/RtfPipe/Parser.cs b/RtfPipe/Parser.cs
index f95f4e6..44588b5 100644
--- a/RtfPipe/Parser.cs
+++ b/RtfPipe/Parser.cs
@@ -295,10 +296,32 @@ private IToken ReadControlWord()
         }
       }
 
+
       if (_reader.Peek() == ' ')
         _reader.Read();
 
-      return GetControlWord(name, number);
+
+      // Shape properties are in the form of 
+      // {\sp{\sn fLayoutInCell}{\sv 1}}}
+
+      // Annoyingly sv can also contain a new item under it...
+      // eg {\sp{\sn pib}{\sv {\pict\picscalex100\picscaley100\piccropl0\piccropr0\piccropt0\piccropb0\picw5874\pich2355\picwgoal3330\pichgoal1335\pngblip\bliptag657767501{\*\blipuid 2734bc4d38f27beeaf9db7be2dadc0c7}
+      // Loop through until we get to '{' or '}' (start of new group or close of current group)
+      string propertyName = string.Empty;
+      if (name == "sn" || name == "sv")
+      {
+        _controlBuffer.Length = 0;
+
+        while ((char)_reader.Peek() != '{' && (char)_reader.Peek() != '}')
+        {
+          _controlBuffer.Append((char)_reader.Read());
+        }
+        propertyName = _controlBuffer.ToString();
+        _controlBuffer.Length = 0;
+      }
+
+
+      return GetControlWord(name, number, propertyName);
     }
 
     private IToken ConsumeToken(IToken token)
```

**Comment by erdomke** [comment]
The general flow of the code is:

1. `Parser.Tokens()` generates a lightly processed flat stream of RTF tokens. While color and font values are interpreted and certain equivalent token types are converted to an identical representation, no other processing takes place here.
2. `Parser.Parse()` takes the token stream and generates a tree structure (represented by the `Document` class) by interpreting all of the group starts and ends.
3. `Interpreter` traverses the tree structure and writes out the appropriate HTML.

Where you placed the code is in the first tokenization step. I would think it would be easier to do this interpretation elsewhere. In particular, after you have the `Document` from step 2, you can traverse the groups. Each group has a `Destination` property indicating the first tag. From there you can act on the information.
