### ISSUE TITLE
Null object

### ISSUE THREAD

**Issue by dannyrb** [erdomke/RtfPipe#2]
```
{System.NullReferenceException: Object reference not set to an instance of an object.
   at RtfPipe.Rtf.BuildHtmlContent(IRtfGroup content, XmlWriter writer)
   at RtfPipe.Rtf.ToHtml(RtfSource source, XmlWriter writer, RtfHtmlWriterSettings settings)
   at RtfPipe.Rtf.ToHtml(RtfSource source, RtfHtmlWriterSettings settings)}
```

When trying to parse:

```
"{\\rtf1\\ansi\\ansicpg1252\\uc1\\htmautsp\\deff2{\\fonttbl{\\f0\\fcharset0 Times New Roman;}{\\f2\\fcharset0 GenericSansSerif;}}{\\colortbl\\red0\\green0\\blue0;\\red255\\green255\\blue255;}\\loch\\hich\\dbch\\pard\\plain\\ltrpar\\itap0{\\lang1033\\fs18\\f2\\cf0 \\cf0\\ql{\\f2 {\\ltrch Alyssa Mourning}\\li0\\ri0\\sa0\\sb0\\fi0\\ql\\par}\r\n}\r\n}"
```

Using `Rtf.ToHtml(rtfAsString);`

**Comment by dannyrb** [comment]
I receive a similar error when attempting:

`Rtf.ToHtml("{\\rtf1\\ansi\\b Hello World\\b0 }");`

It may be worth noting that I'm using dotnent core

**Comment by DumboJetEngine** [comment]
In my case the problem was a hidden inner exception:

```
'Windows-1252' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
```

I will try to fix it now...
