### ISSUE TITLE
Stack empty exception

### ISSUE THREAD

**Issue by Mario-Eis** [erdomke/RtfPipe#26]
Since version 1.0.0.x on Nuget (last known working version is 0.7.0.6 from Nuget) there is a stack empty exception for some of my RTF strings. 

```
System.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Peek()
   at RtfPipe.Parser.<Tokens>d__16.MoveNext()
   at RtfPipe.Parser.Parse()
   at RtfPipe.Rtf.ToHtml(RtfSource source, XmlWriter writer, RtfHtmlSettings settings)
   at RtfPipe.Rtf.ToHtml(RtfSource source, RtfHtmlSettings settings)
```

Here is an example:

```
{\rtf1\ansi\ansicpg1252\deff0\deflang1033\fs20{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}
{\f99\froman\fcharset0\fprq2{\*\panose 02020603050405020304}Arial;}{\f100\fnil\fcharset2 Symbol;}{\f101\fnil\fcharset2 Wingdings;}{\f102\fcharset204{\*\fname Courier New;}Courier New CYR;}{\f103\fcharset0 Arial;}}
{\colortbl ;\red0\green0\blue0;\red51\green102\blue255;}
\paperw12240\paperh15840\margl1417\margr1134\margt1134\margb1134
\pard\sb100\sa100\sbauto1\saauto1\fs20\lang1033
ist Ersatzabruf für 4200028332 warAN 68595 bez 12.261,20- Re 111607-7105658060-ok !!\pard}}
```

**Comment by erdomke** [comment]
The problem appears to be an extra closing brace at the end of the RTF document. This should be addressed in the latest release.
