### ISSUE TITLE
A backslash in the content causes the conversion to fail

### ISSUE THREAD

**Issue by connectmed** [erdomke/RtfPipe#29]
When a backslash is present in the content, the conversion from rtf to html fails.

example rtf snippet:

Copies:\par 
Dr G. Smith\par \par 
PELVIS \ LEFT HIP 01/04/2019 Reference: 1234556 NHI: ABC1234\par 
AC Reference: 12312443423\par \par \par 

This causes:
System.NotSupportedException: Specified method is not supported.
   at RtfPipe.Parser.<Tokens>d__18.MoveNext()
   at RtfPipe.Parser.Parse()
   at RtfPipe.Rtf.ToHtml(RtfSource source, XmlWriter writer, RtfHtmlSettings settings)
   at RtfPipe.Rtf.ToHtml(RtfSource source, RtfHtmlSettings settings)

As a workaround, I can use an SQL REPLACE to remove the backslash before it processed by rtfpipe.

**Comment by erdomke** [comment]
A fix for this is being released.
