### ISSUE TITLE
RtfPipe crashes when trying to convert the following value

### ISSUE THREAD

**Issue by MarvinKlein1508** [erdomke/RtfPipe#49]
It crashes everytime with a null reference exception when I try to parse this string to html:
`{\rtf1\ansi\ansicpg1252\deff0\deflang1031{\fonttbl{\f0\fnil\fcharset0 Verdana;} 
\viewkind4\uc1\pard\f0\fs18 5% Auf Patronen \par
\f1\par
}
 {\f1\fnil Verdana;}}`

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at RtfPipe.HtmlWriter.TagContext.WriteCss(StringBuilder builder, Font font)
   at RtfPipe.HtmlWriter.TagContext.ToString()
   at RtfPipe.HtmlWriter.WriteTag(TagContext tag)
   at RtfPipe.HtmlWriter.EnsureSpans(FormatContext format)
   at RtfPipe.HtmlWriter.AddText(FormatContext format, String text)
   at RtfPipe.Interpreter.ToHtmlGroup(Document doc, Group group, Boolean processRtf)
   at RtfPipe.Interpreter.ToHtmlGroup(Document doc, Group group, Boolean processRtf)
   at RtfPipe.Interpreter.ToHtml(Document doc, RtfHtmlSettings settings)
   at RtfPipe.Rtf.ToHtml(RtfSource source, RtfHtmlSettings settings)
   at RtfConverter.Program.Main(String[] args) in F:\wk5-programs\RtfConverter\Program.cs:line 31

**Comment by erdomke** [comment]
This should now be resolved after the latest release.
