### ISSUE TITLE
System.ArgumentException Message=Parameter is not valid.   Source=System.Drawing

### ISSUE THREAD

**Issue by MartinAmsinck** [erdomke/RtfPipe#66]
Hi i get an exception when trying to run Rtf.ToHtml() with the attached rtf value
[rtf.txt](https://github.com/erdomke/RtfPipe/files/6286291/rtf.txt)

```
 StackTrace:
   at System.Drawing.Bitmap..ctor(Stream stream)
   
   at RtfPipe.RtfHtmlSettings.DataUri(Picture picture)

   at RtfPipe.Model.HtmlVisitor.Visit(Picture image)

   at RtfPipe.Model.HtmlVisitor.Visit(Element element)

   at RtfPipe.Model.HtmlVisitor.Visit(Element element)

   at RtfPipe.Model.HtmlVisitor.Visit(Element element)

   at RtfPipe.Model.HtmlVisitor.Visit(Element element)

   at RtfPipe.Model.HtmlVisitor.Visit(RtfHtml document)

   at RtfPipe.Rtf.ToHtml(RtfSource source, XmlWriter writer, RtfHtmlSettings settings)

   at RtfPipe.Rtf.ToHtml(RtfSource source, RtfHtmlSettings settings)
```
I'm running the latest version

**Comment by MartinAmsinck** [comment]
My bad - fixed with an upgrade to the newest version

**Comment by MartinAmsinck** [comment]
Found the issue(again), It is an azure issue.
There's GDI+ restrictions on Azure.

[System.drawing is being blocked by the system. (https://stackoverflow.com/questions/40924122/can-system-drawing-be-used-in-an-azure-web-site) ](https://stackoverflow.com/questions/40924122/can-system-drawing-be-used-in-an-azure-web-site)

Any ideas for a workaround here?

**Comment by janhjordie** [comment]
I have same issue. Only a problem on Azure. As Martin mentions, Azure Web App's, and also Azure Functions, due to security restrictions, don't have access to the kernel GDI. So some functions in System.Drawing is not available

**Comment by erdomke** [comment]
The workaround is to pass in an `RtfHtmlSettings` object where you provide your own `ImageUriGetter` callback. In that callback, you can return whatever URL you want for any given picture, perhaps using a different library of your choosing. I will try to document this better soon.
