### ISSUE TITLE
OutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime

### ISSUE THREAD

**Issue by antibios** [erdomke/RtfPipe#68]
When processing the following RTF I get a date time conversion error.  Is there a way to ignore the info command:
```
info{\creatim\yr2021\mo7\dy13\hr10\min51}{\revtim\yr2021\mo7\dy13\hr10\min52}{\printim\yr0\mo0\dy0\hr0\min0}}
```
[CreateTimeError.txt](https://github.com/erdomke/RtfPipe/files/6805983/CreateTimeError.txt)

**Comment by NicoAiko** [comment]
To be precise, (for me) the error is the following:

```cs
Unhandled exception. System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime
  at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
  at RtfPipe.Parser.ParseInfo(Document document, Group info)
  at RtfPipe.Parser.Parse()
  at RtfPipe.Rtf.ToHtml(RtfSource source, XmlWriter writer, RtfHtmlSettings settings)
  at RtfPipe.Rtf.ToHtml(RtfSource source, RtfHtmlSettings settings)
```

**Comment by NicoAiko** [comment]
I'd say the problem lies with https://github.com/erdomke/RtfPipe/blob/master/RtfPipe/Parser.cs Lines 125-131-ish.

There is no checking of the date values, so it crashes at malformed RTF content.

**Comment by lavrentius-dev** [comment]
I second this. I get this exception when trying to Rtf2Html files exported from Collab (LibreOffice). Don't know how those dates in y-m-d format ended up in the exported rtf file as they are not in my text. Anyway, this is a major issue as I have no control over the export mechanism and the conversion fails. Waiting for the fix in the next release.
