### ISSUE TITLE
Throw “Stack empty” Exception when do parsing

### ISSUE THREAD

**Issue by FB99** [erdomke/RtfPipe#72]
In some cases, exception will be thrown in Parser.cs, line 99.
`groups.Peek().Contents.Add(token);`

**Comment by kunom** [comment]
Same here. The RTF document was created by Doxygen 1.16.1, it can be opened with MS Word.

```
System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Peek()
   at RtfPipe.Parser.Tokens()+MoveNext()
   at RtfPipe.Parser.Parse()
   at RtfPipe.Rtf.ToHtml(RtfSource source, XmlWriter writer, RtfHtmlSettings settings)
   at RtfPipe.Rtf.ToHtml(RtfSource source, RtfHtmlSettings settings)
```
